#include "application/period_manager.h"

#include "domain/runtime_error.h"
#include "ports/clock.h"
#include "ports/id_generator.h"
#include "ports/period_store.h"

#include <utility>

namespace agent {

PeriodManager::PeriodManager(PeriodStore& store, Clock& clock, IdGenerator& ids)
    : store_(store), clock_(clock), ids_(ids) {
    // Eager load: a brand-new install simply reads an empty list.
    auto loaded = store_.read_all();
    if (loaded.has_value()) {
        for (auto& p : loaded.value()) {
            const auto id = p.period_id;
            periods_.emplace(id, std::move(p));
        }
    }
    // Read failure is non-fatal: we start with an empty cache and let
    // the next flush attempt surface the error.
}

void PeriodManager::flush_locked() {
    auto snapshot = snapshot_locked();
    auto write_result = store_.write_all(snapshot);
    (void)write_result;  // Caller handles via return values.
}

std::vector<Period> PeriodManager::snapshot_locked() const {
    std::vector<Period> out;
    out.reserve(periods_.size());
    for (const auto& [_, p] : periods_) out.push_back(p);
    return out;
}

Result<Period> PeriodManager::open_period() {
    std::lock_guard<std::mutex> lock(mutex_);
    Period period;
    period.period_id = ids_.next_correlation_id();
    period.started_at_utc = clock_.now_utc();
    period.state = PeriodState::Open;
    periods_.emplace(period.period_id, period);
    auto write = store_.write_all(snapshot_locked());
    if (!write.has_value())
        return Result<Period>::failure(write.error());
    return Result<Period>::success(period);
}

Result<void> PeriodManager::attach_session(const std::string& period_id,
                                          const std::string& session_id) {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = periods_.find(period_id);
    if (it == periods_.end())
        return Result<void>::failure(
            {ErrorCode::InvalidInput, "period not found", false});
    if (it->second.state == PeriodState::Closed)
        return Result<void>::failure(
            {ErrorCode::InvalidTransition, "period is closed", false});
    auto& sessions = it->second.session_ids;
    // Idempotent: same session re-attaching doesn't double-count.
    if (std::find(sessions.begin(), sessions.end(), session_id) ==
        sessions.end()) {
        sessions.push_back(session_id);
        ++it->second.sessions_count;
    }
    auto write = store_.write_all(snapshot_locked());
    if (!write.has_value()) return write;
    return Result<void>::success();
}

Result<void> PeriodManager::close_period(const std::string& period_id) {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = periods_.find(period_id);
    if (it == periods_.end())
        return Result<void>::failure(
            {ErrorCode::InvalidInput, "period not found", false});
    it->second.state = PeriodState::Closed;
    it->second.ended_at_utc = clock_.now_utc();
    auto write = store_.write_all(snapshot_locked());
    if (!write.has_value()) return write;
    return Result<void>::success();
}

Result<void> PeriodManager::append_summary(const std::string& period_id,
                                          const std::string& summary) {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = periods_.find(period_id);
    if (it == periods_.end())
        return Result<void>::failure(
            {ErrorCode::InvalidInput, "period not found", false});
    if (!it->second.episodic_summary.empty())
        it->second.episodic_summary += "\n\n";
    it->second.episodic_summary += summary;
    auto write = store_.write_all(snapshot_locked());
    if (!write.has_value()) return write;
    return Result<void>::success();
}

Result<void> PeriodManager::accumulate_tokens(const std::string& period_id,
                                              std::size_t tokens) {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = periods_.find(period_id);
    if (it == periods_.end())
        return Result<void>::failure(
            {ErrorCode::InvalidInput, "period not found", false});
    it->second.tokens_in_period += tokens;
    // Token bookkeeping doesn't need to hit disk every single turn —
    // it's regenerated by Stage 6 from RuntimeUsageDelta on each
    // process start. So we skip the write here.
    return Result<void>::success();
}

Result<std::vector<Period>> PeriodManager::list_open_periods() const {
    std::lock_guard<std::mutex> lock(mutex_);
    std::vector<Period> out;
    for (const auto& [_, p] : periods_) {
        if (p.state == PeriodState::Open) out.push_back(p);
    }
    return Result<std::vector<Period>>::success(std::move(out));
}

Result<std::optional<Period>> PeriodManager::find(
    const std::string& period_id) const {
    std::lock_guard<std::mutex> lock(mutex_);
    auto it = periods_.find(period_id);
    if (it == periods_.end())
        return Result<std::optional<Period>>::success(std::nullopt);
    return Result<std::optional<Period>>::success(it->second);
}

std::size_t PeriodManager::cached_period_count() const {
    std::lock_guard<std::mutex> lock(mutex_);
    return periods_.size();
}

}  // namespace agent
