cmake_minimum_required(VERSION 3.21)

# This script has one fixed staging target, derived from its own checkout. It
# never reads configuration contents and never invokes a provider or program.
get_filename_component(source_root "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
set(expected_dir "${source_root}/out/AgentFramework-Ready")
if(NOT DEFINED AGENT_READY_DIR)
    set(AGENT_READY_DIR "${expected_dir}")
endif()
if(NOT AGENT_READY_CONFIG STREQUAL "Release")
    message(FATAL_ERROR "A Release build is required for the Ready package")
endif()
if(NOT IS_ABSOLUTE "${AGENT_READY_DIR}")
    message(FATAL_ERROR "Only the exact Ready staging directory may be recreated")
endif()
cmake_path(SET stage_dir NORMALIZE "${AGENT_READY_DIR}")
if(EXISTS "${stage_dir}")
    file(REAL_PATH "${stage_dir}" resolved_stage)
else()
    set(resolved_stage "${stage_dir}")
endif()
if(NOT stage_dir STREQUAL expected_dir OR NOT resolved_stage STREQUAL expected_dir
   OR IS_SYMLINK "${source_root}/out" OR IS_SYMLINK "${stage_dir}")
    message(FATAL_ERROR "Only the exact Ready staging directory may be recreated")
endif()

if(NOT DEFINED AGENT_READY_ENV_FILE OR NOT EXISTS "${AGENT_READY_ENV_FILE}"
   OR IS_DIRECTORY "${AGENT_READY_ENV_FILE}" OR IS_SYMLINK "${AGENT_READY_ENV_FILE}")
    message(FATAL_ERROR "A local environment file is required to explicitly package Ready")
endif()
file(SIZE "${AGENT_READY_ENV_FILE}" env_size)
if(env_size EQUAL 0)
    message(FATAL_ERROR "A nonempty local environment file is required to explicitly package Ready")
endif()
string(REPLACE "|" ";" runtime_dlls "${AGENT_READY_DLLS}")
if(NOT DEFINED AGENT_READY_EXE OR runtime_dlls STREQUAL "")
    message(FATAL_ERROR "The built executable and runtime DLL list are required")
endif()
list(LENGTH runtime_dlls runtime_dll_count)
if(NOT runtime_dll_count EQUAL 2)
    message(FATAL_ERROR "Ready requires exactly two runtime DLLs")
endif()
get_filename_component(exe_name "${AGENT_READY_EXE}" NAME)
if(NOT exe_name STREQUAL "AgentFramework.exe")
    message(FATAL_ERROR "The Ready artifact must be AgentFramework.exe")
endif()
set(artifact_names "${exe_name}" ".env")
set(runtime_dll_names "")
foreach(dll IN LISTS runtime_dlls)
    get_filename_component(dll_name "${dll}" NAME)
    if(NOT dll_name MATCHES "\\.[dD][lL][lL]$")
        message(FATAL_ERROR "The runtime dependency list must contain only DLL files")
    endif()
    if(dll_name IN_LIST artifact_names)
        message(FATAL_ERROR "Ready package filenames must be unique")
    endif()
    list(APPEND artifact_names "${dll_name}")
    string(TOLOWER "${dll_name}" dll_name_lower)
    list(APPEND runtime_dll_names "${dll_name_lower}")
endforeach()
list(SORT runtime_dll_names)
set(expected_runtime_dll_names "cpr.dll" "libcurl.dll")
list(SORT expected_runtime_dll_names)
if(NOT runtime_dll_names STREQUAL expected_runtime_dll_names)
    message(FATAL_ERROR "Ready requires exactly cpr.dll and libcurl.dll")
endif()
list(LENGTH artifact_names artifact_count)
if(NOT artifact_count EQUAL 4)
    message(FATAL_ERROR "Ready must contain exactly four managed files")
endif()

foreach(input IN ITEMS "${AGENT_READY_EXE}" "${AGENT_READY_ENV_FILE}" ${runtime_dlls})
    if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}" OR IS_SYMLINK "${input}")
        message(FATAL_ERROR "A required Ready package input is not a regular file")
    endif()
    file(REAL_PATH "${input}" resolved_input)
    cmake_path(IS_PREFIX stage_dir "${resolved_input}" NORMALIZE input_is_staged)
    if(input_is_staged)
        message(FATAL_ERROR "Ready package inputs must be outside the staging directory")
    endif()
endforeach()

# Refuse rather than deleting anything that is not one of the explicitly
# managed artifacts. Existing managed files are overwritten in place; no
# recursive deletion is used, so application-created runtime state survives a
# rejected rebuild.
if(EXISTS "${stage_dir}")
    if(NOT IS_DIRECTORY "${stage_dir}")
        message(FATAL_ERROR "The exact Ready staging path must be a directory")
    endif()
    file(GLOB existing_entries LIST_DIRECTORIES true RELATIVE "${stage_dir}"
        "${stage_dir}/*" "${stage_dir}/.*")
    foreach(entry IN LISTS existing_entries)
        if(NOT entry IN_LIST artifact_names)
            message(FATAL_ERROR
                "Ready staging contains an unmanaged entry; refusing to replace it")
        endif()
        if(IS_DIRECTORY "${stage_dir}/${entry}" OR
           IS_SYMLINK "${stage_dir}/${entry}")
            message(FATAL_ERROR "Ready managed artifact paths must be regular files")
        endif()
    endforeach()
endif()
file(MAKE_DIRECTORY "${stage_dir}")
file(COPY_FILE "${AGENT_READY_EXE}" "${stage_dir}/${exe_name}")
foreach(dll IN LISTS runtime_dlls)
    get_filename_component(dll_name "${dll}" NAME)
    file(COPY_FILE "${dll}" "${stage_dir}/${dll_name}")
endforeach()
file(COPY_FILE "${AGENT_READY_ENV_FILE}" "${stage_dir}/.env")
message(STATUS "Ready package staged: ${stage_dir}")
