cmake_minimum_required(VERSION 3.21)

foreach(required AGENT_READY_EXE AGENT_READY_DLLS AGENT_READY_DIR AGENT_PROCESS_TEST_EXE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Ready package verification is missing ${required}")
    endif()
endforeach()
if(NOT AGENT_READY_CONFIG STREQUAL "Release")
    message(FATAL_ERROR "A Release build is required for Ready package verification")
endif()
if(NOT IS_DIRECTORY "${AGENT_READY_DIR}" OR IS_SYMLINK "${AGENT_READY_DIR}")
    message(FATAL_ERROR "The Ready package must be a regular directory")
endif()
get_filename_component(exe_name "${AGENT_READY_EXE}" NAME)
string(REPLACE "|" ";" runtime_dlls "${AGENT_READY_DLLS}")
list(LENGTH runtime_dlls runtime_dll_count)
if(NOT runtime_dll_count EQUAL 2)
    message(FATAL_ERROR "Ready requires exactly two runtime DLLs")
endif()
set(expected_files ".env" "${exe_name}")
set(runtime_dll_names "")
foreach(dll IN LISTS runtime_dlls)
    get_filename_component(dll_name "${dll}" NAME)
    list(APPEND expected_files "${dll_name}")
    string(TOLOWER "${dll_name}" dll_name_lower)
    list(APPEND runtime_dll_names "${dll_name_lower}")
endforeach()
list(SORT runtime_dll_names)
set(expected_runtime_dll_names "cpr.dll" "libcurl.dll")
list(SORT expected_runtime_dll_names)
if(NOT runtime_dll_names STREQUAL expected_runtime_dll_names)
    message(FATAL_ERROR "Ready requires exactly cpr.dll and libcurl.dll")
endif()
list(LENGTH expected_files expected_file_count)
if(NOT expected_file_count EQUAL 4)
    message(FATAL_ERROR "Ready must contain exactly four files")
endif()
file(GLOB actual_files RELATIVE "${AGENT_READY_DIR}" "${AGENT_READY_DIR}/*" "${AGENT_READY_DIR}/.*")
list(SORT actual_files)
list(SORT expected_files)
if(NOT actual_files STREQUAL expected_files)
    message(FATAL_ERROR "Ready package inventory mismatch: only the EXE, required DLLs, and .env are allowed")
endif()
foreach(name IN LISTS actual_files)
    if(IS_DIRECTORY "${AGENT_READY_DIR}/${name}" OR IS_SYMLINK "${AGENT_READY_DIR}/${name}")
        message(FATAL_ERROR "Ready package entries must be regular files")
    endif()
endforeach()
# Metadata only: no file(READ), hash, contents, or startup using the real .env.
file(SIZE "${AGENT_READY_DIR}/.env" env_size)
if(env_size EQUAL 0)
    message(FATAL_ERROR "Ready package .env must be nonempty")
endif()
foreach(input IN ITEMS "${AGENT_READY_EXE}" ${runtime_dlls})
    get_filename_component(name "${input}" NAME)
    file(SHA256 "${input}" built_hash)
    file(SHA256 "${AGENT_READY_DIR}/${name}" staged_hash)
    if(NOT staged_hash STREQUAL built_hash)
        message(FATAL_ERROR "Ready package hash mismatch: ${name}")
    endif()
    message(STATUS "Ready byte identity: ${name} SHA256=${staged_hash}")
endforeach()

# The executable tests always pass an explicit synthetic loopback config. A
# second EXE/DLL-only deployment tests colocated discovery with a synthetic .env
# and a different cwd. They also check .env is regular, nonempty, and single-link.
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "AGENT_PROCESS_TEST_EXE=${AGENT_READY_DIR}/${exe_name}"
    "${AGENT_PROCESS_TEST_EXE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Ready credential-free executable verification failed (${result}): ${output}${error}")
endif()
message(STATUS "${output}")
message(STATUS "Ready package verified: ${actual_files}; real .env inspected by metadata only")
